### ISSUE TITLE
Out of memory exception on multipart

### ISSUE THREAD

**Issue by wdayanand** [google/volley#106]
I used volley for upload video it works if file size is small like 5 mb but if I try with large file it giving OOM exception .
Please help how I can upload large files with volley

**Comment by wdayanand** [comment]
@Override
    public byte[] getBody() throws AuthFailureError {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        DataOutputStream dos = new DataOutputStream(bos);

        try {
            // populate text payload
            Map<String, String> params = getParams();
            if (params != null && params.size() > 0) {
                textParse(dos, params, getParamsEncoding());
            }

            // populate data byte payload
            Map<String, DataPart> data = getByteData();
            if (data != null && data.size() > 0) {
                dataParse(dos, data);
            }

            // close multipart form data after text and file data
            dos.writeBytes(twoHyphens + boundary + twoHyphens + lineEnd);

            return bos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
========================$$
It crashed on= return bos.toByteArray()

**Comment by jpd236** [comment]
I'm afraid Volley's architecture is such that it is not really built for large requests/responses. It inherently requires that the full request/response be storable in memory, and for video uploads it makes far more sense to stream them incrementally over the network from another source (i.e. disk), to support resume of partial uploads, etc, in a way that Volley's API inherently doesn't support. This is noted in the [documentation](https://developer.android.com/training/volley/index.html), mostly for downloads but also affecting large uploads:

"Volley is not suitable for large download or streaming operations, since Volley holds all responses in memory during parsing"

I recommend using a different library/paradigm for this use case that doesn't try to load the full video in memory and which supports resumable uploads.

**Comment by wdayanand** [comment]
Thanks
