### ISSUE TITLE
Request.finish() may pass useless string to MarkerLog

### ISSUE THREAD

**Issue by joebowbeer** [google/volley#115]
In Request.finish(), the Runnable is calling toString on itself instead of the Request object:

```
    mainThread.post(new Runnable() {
        @Override
        public void run() {
            mEventLog.add(tag, threadId);
            mEventLog.finish(this.toString());
        }
    });
```

Should be `Request.this.toString()`

Also, it would be more robust and leak-resistant if this Runnable were a static nested class that held no reference to the outer Request instance.

**Comment by jpd236** [comment]
This will be resolved by https://github.com/google/volley/pull/112, which I plan to merge after cutting 1.1.0 final.

It would probably be reasonable to grab the string up front to avoid leaking a reference to the Request, but ultimately this is debug only code (gated by MarkerLog.ENABLED) and any leak would be very short lived since it's just a quick runnable posted to the main thread.

**Comment by jpd236** [comment]
https://github.com/google/volley/pull/112 is merged.
