### ISSUE TITLE
HTTP headers in Android 8.0

### ISSUE THREAD

**Issue by avdicSaid** [google/volley#116]
Hello,
Is there any update on Volley regarding the headers in Android 8.0 (26)?

This doesn't work properly on the last Android version.
 @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                Map<String, String> params = new HashMap<String, String>();
                params.put("x-api-key", App.apiAuth);
                return params;
            }

Thanks in advance

**Comment by jpd236** [comment]
There should be no change in behavior across platform versions. We certainly have apps that are overriding getHeaders() in this manner and are working perfectly fine on Android O.

More details would be needed to track down any issues here, e.g.:

- Version of Volley
- Device being used (or is it emulator)
- Ideally, a fully-working sample to reproduce the problem, but at least more information about what your app is doing like the HttpStack implementation you're using.
- Does it reproduce on older versions of Android? With older versions of Volley (if you're using 1.1.0-rc1 or the latest code rather than 1.0.0)?

**Comment by avdicSaid** [comment]
It's work fine on all devices but Android 8.0.
In Android studio simulator for 8.0 it's work too.

So, problem is just with Android Oreo.
It's using    compile 'com.android.volley:volley:1.1.0-rc1'
Device is Pixel 1.

App works fine when I disable authorization from API, but with authorization on the API side I have to add authorization header in the app, and app isn't able to download anything from the API.
That's the problem, and it occurs only on Android 8.0.

**Comment by jpd236** [comment]
Like I mentioned, we have apps that specify authentication headers and work fine, and the fact that it's only one particular device running Android O rather than Android 8.0 in general (since the emulator works fine) suggests it's likely to be a problem on that device specifically. (Not necessarily with the model of device, as our apps work fine with authenticated APIs on Pixel too, but with the particular state of things on that device).

My suggestion would be to try and intercept the requests from both a working device and a not working device and see what they contain. Ultimately all Volley does is assemble an issue an HTTP request and send it to the server, so if one request works and the other doesn't then there is going to be some difference in the two requests that is leading to a behavior change.

**Comment by avdicSaid** [comment]
Yeah, I'm sorry, it was issue related to the device. After resetting to factory settings, it works fine.

**Comment by assifgit** [comment]
How it resolved, I am facing the same issue.
Struggling to just pass header in android 8.0 device.
thanks in advance

**Comment by avdicSaid** [comment]
Just use last version of volley and it will work fine.
Pass headers in this form:

`String requestUrl = App.getSettings().getApiurl() + App.getContext().getResources().getString(R.string.articles_url) + "/" + newsId;
            
StringRequest newsContentRequest = new StringRequest(Request.Method.GET, requestUrl, new Response.Listener<String>() {
	@Override
	public void onResponse(String response) {

		Logs.log(TAG, Logs.IMPORT, "contentRequest response : " + response);
		ArticleResponse articleResponse = new Gson().fromJson(response, ArticleResponse.class);

	   // do something
	}
},
		new Response.ErrorListener() {
			@Override
			public void onErrorResponse(VolleyError error) {
				Logs.log(TAG, Logs.IMPORT, "volley request error message" + error);
				Logs.log(TAG, Logs.IMPORT, "loadMoreContentRequest : " + new Gson().toJson(error));
			}
		}
) {
	@Override
	public Map<String, String> getHeaders() throws AuthFailureError {
		Map<String, String> params = new HashMap<String, String>();
		params.put("x-api-key", App.apiAuth);
		return params;
	}
};


newsContentRequest.setRetryPolicy(getRetryPolicy());
newsContentRequest.setTag("NewsId:" + newsId);
getQueue().add(newsContentRequest);`

**Comment by assifgit** [comment]
Thanks, But I am passing the same way.
Seems some issue on the server side.
