### ISSUE TITLE
All requests finished callback

### ISSUE THREAD

**Issue by ferglezt** [google/volley#126]
I have got into situations where it was necessary to add many requests into a RequestQueue and get a callback when they were all finished. I have solved this problem with workarounds like using RequestQueue.RequestFinishedListener and keep count of the requests I'm adding, but I was wondering if  it'd be a good idea to implement this callback as a new feature of RequestQueue.

**Comment by jpd236** [comment]
It feels to me like it'd be a bit more complex than belongs in the core of Volley without more interested clients, and it should be reasonable enough to implement on top of RequestFinishedListener.

What I think I'd do, rather than using a counter, is something like:

```
public abstract class AllRequestsFinishedListener<T> implements RequestQueue.RequestFinishedListener<T> {
    private final Set<Request<T>> mRequests = new ArraySet<>();

    public AllRequestsFinishedListener(Request<T>... requests) {
        synchronized (mRequests) {
            mRequests.addAll(Arrays.asList(requests));
        }
    }

    @Override
    public void onRequestFinished(Request<T> request) {
        synchronized (mRequests) {
            mRequests.remove(request);
            if (mRequests.isEmpty()) {
                onAllRequestsFinished();
            }
        }
    }

    public abstract void onAllRequestsFinished();
}
```
Then you can add it as a listener before dispatching your requests, and remove it when onAllRequestsFinished is called.
