### ISSUE TITLE
Out of memory with Volley 1.1.0

### ISSUE THREAD

**Issue by megataps** [google/volley#127]
I got this crash when upgrade to version 1.1.0

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 335787708 byte allocation with 1588101 free bytes and 507MB until OOM
       at java.util.ArrayList.(ArrayList.java)
       at com.android.volley.toolbox.DiskBasedCache.readHeaderList(SourceFile:606)
       at com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader(SourceFile:437)
       at com.android.volley.toolbox.DiskBasedCache.initialize(SourceFile:170)
       at com.android.volley.CacheDispatcher.run(SourceFile:92)

**Comment by joebowbeer** [comment]
I see now that I overlooked that case. The unprotected ArrayList allocation is causing OOME due to a bogus size in the cache:

`new ArrayList<Header>(size);`

The fix is to not trust the size:

`new ArrayList<Header>();`

Then the subsequent read calls will run off the end of the input stream, which is an exception that will be caught and handled by deleting the corrupted cache entry.

I'll post a fix (and a new unit test!)

**Comment by joebowbeer** [comment]
See #12

In the next version of the on-disk cache, the header size should be persisted as unsigned short..

**Comment by jpd236** [comment]
This is now in 1.1.1-SNAPSHOT builds. It would be excellent if someone encountering this issue could update to 1.1.1-SNAPSHOT and verify the fix. Thanks!

**Comment by j-t-h** [comment]
Do you have an update when 1.1.1 with be released and not in the snapshot builds? I am holding an app release to wait on this fix.

**Comment by jpd236** [comment]
We don't have a planned date at this time - there are [more open issues](https://github.com/google/volley/milestone/4) to investigate first, unless there becomes an urgent need to cut an official release, e.g. for a security issue or major bug. That being said, official releases at this point really are just SNAPSHOT builds which are promoted to official release numbers, so there's not much difference in practice between depending on a particular snapshot and having us designate that particular snapshot as a particular release.

**Comment by joebowbeer** [comment]
I suggest releasing it sooner rather than later. The mcxiaoke folks are also looking for a fix:

https://github.com/mcxiaoke/android-volley/issues/37

If releases are really just promoted snapshots, is there any reason not to release more often? The problem with SNAPSHOT is that it might break the next time something is merged to master.

**Comment by jpd236** [comment]
You can depend on a particular fixed SNAPSHOT version to avoid having breakages if a new commit is made to master. Though in general we're trying to keep master fairly stable.

**Comment by j-t-h** [comment]
Can you give an example of this?

Would it just be:
compile 'com.android.volley:volley:1.1.1-SNAPSHOT' or something different?

**Comment by j-t-h** [comment]
Can you give an example of this?

Would it just be:

compile 'com.android.volley:volley:1.1.1-SNAPSHOT' or something different?

**Comment by jpd236** [comment]
For example, the latest snapshot from:

https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/volley/volley/1.1.1-SNAPSHOT/

can be referenced via Maven as:

compile 'com.android.volley:volley:1.1.1-20171227.180452-3'

**Comment by PhalugunaRao** [comment]
is this issue fixed for me also getting 
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1751327368 byte allocation with 23517303 free bytes and 489MB until OOM, target footprint 47034607, growth limit 536870912
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:327)
       at com.android.volley.toolbox.DiskBasedCache.readString(DiskBasedCache.java:545)
       at com.android.volley.toolbox.DiskBasedCache.readStringStringMap(DiskBasedCache.java:567)
       at com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader(DiskBasedCache.java:408)
       at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:118)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:110)

**Comment by jpd236** [comment]
That stack trace is different from the original issue raised here, and seems less likely to be caused due to corruption. readString() works by storing a long (the size of the string) followed by the bytes of the string. The length of the read is capped to the length of the file on disk as per File#length(). So you would need to have both a file on disk that is at least ~1.63GiB, and the size of the string would have to be less than or equal to that, for it to attempt to allocate a string of that size.

I suppose it's possible that you had corruption in this way, but it strikes me as unlikely, especially given that nobody else has reported quite the same crash. Is it possible you actually managed to store a cache entry that is that huge, and it is now crashing trying to read it? Do you have more details on the circumstances in which you're seeing this?
