### ISSUE TITLE
Volley request handshake failed

### ISSUE THREAD

**Issue by vecihibaltaci** [google/volley#128]
I'm trying to send Get request to HTTPS link. But that gives me an "Handshake failed : noconnection error". Is this a known issue?

**Comment by jpd236** [comment]
It's likely to be an issue with either your server or the device rather than Volley, which is just a thin layer around the underlying HTTP stack.

I recommend seeing if you can reproduce the issue with the underlying HTTP library, e.g. HttpUrlConnection or Apache HTTP.

Feel free to reopen if you are able to reproduce this only with Volley and not with the underlying HTTP client corresponding to the HttpStack you are using with Volley. If so, more details would be much appreciated, e.g. sample code if you can provide it, or more about the device you are using, what version of Android it is running, and what server you are trying to connect to.

**Comment by pedy711** [comment]
@vecihibaltaci did you find a solution for it? Im having the same problem. Please help

**Comment by vecihibaltaci** [comment]
@pedy711 i didn't found any solution but i found the reason of this problem. In my issue, there is a network device between client and server to prevent ddos attack. And the device perceive the https call as ddos attack. So the network device throws the client out of the connection. This causes the problem.

But i can offer a solution for you. 
1- check error type in OnErrorListener from Volley request method
2- if error type is "NoConnectionError" then request again.

i solved it like this. Hopefully helps you.

**Comment by vecihibaltaci** [comment]
@pedy711 I mean On "ErrorListener". you can do it in onErrorResponse Method.
