### ISSUE TITLE
Method.DELETE can not send parametrs

### ISSUE THREAD

**Issue by naeimrezaeian** [google/volley#147]
hi

how i can send parameters when i use delete method ?
i use this code but does not worked

`public Map<String, String> getHeaders() throws AuthFailureError {

                Map<String, String> params = new HashMap<String, String>();

                params.put("Api-Key", "1234");

                params.put("uuid", "4321");

                return params;

            }`

**Comment by jpd236** [comment]
Since this is a Volley bug tracker, rather than a general help forum, this unfortunately probably won't be the most helpful place to look. I'd suggest another help forum like the user group at volley-users@googlegroups.com or a site like StackOverflow.

Headers should work fine with DELETE requests. Request bodies are not supported as noted at https://github.com/google/volley/issues/24.
