### ISSUE TITLE
Cache key doesn't include method (only URL)

### ISSUE THREAD

**Issue by phearme** [google/volley#154]
Hi.
I'm looking how the default `getCacheKey()` method for requests is by default returning only the URL. I have noticed that in the previous repository I was using (mcxiaoke) they decided to include the method along with the URL by default:
https://github.com/mcxiaoke/android-volley/blob/7d0c11b73c17ff81d1b7f4f128bfa9ef997ae62c/src/main/java/com/android/volley/Request.java#L315

Stumbled into this because my server responds differently for the same URL whether my method is GET or POST, and with the current caching volley gives me the same answer (but shouldn't). I perfectly know I can disable the cache or implement my own cache key.

Nevertheless, looking at the RFC here:
https://tools.ietf.org/html/rfc7234#page-6
I state:
`The primary cache key consists of the request method and target URI.
   However, since HTTP caches in common use today are typically limited
   to caching responses to GET, many caches simply decline other methods
   and use only the URI as the primary cache key.`

I interpreted as: the method should be included in the cache key, or the cache should be enabled by default only for GET methods. But clearly not: the cache should be enabled by default for the same URL and for different methods, unless I am mistaken?

**Comment by jpd236** [comment]
More context here:

https://github.com/mcxiaoke/android-volley/issues/67

I agree this seems like a bug. We'd have to be careful about changing it though as doing so would invalidate all cache entries, and it's not immediately obvious how we could safely migrate data over.

In the mean time, as you noted, a workaround would be to implement your own cache key or disable caching for non-GET requests.

**Comment by phearme** [comment]
For existing cache entries, you would have to check if you can get the method of the oroginal requests, and if you can't I don't really see how you could do anything else than invalidate all cache entries which is harsh I agree.

**Comment by lucasiturbide** [comment]
I wrote an issue regarding this matter, and realized that this one is the same.
I found that when doing SOAP API calls, that uses the same service URL and POST method, will try to deliver the same object for different requests, and it's causing a `ClassCastException` in our system.
I had to disable the cache in our child Request class.
I agree with the proposed solution to set the `mShouldCache` value to false for anything that is not GET.

**Comment by phearme** [comment]
@lucasiturbide also waiting for this to get fixed. In the meanwhile, I have to disable cache completely in my app.

**Comment by jpd236** [comment]
The RFC permits caching of responses to methods other than GET, so disabling the cache for non-GET methods would risk breaking apps that are dependent on that behavior (and which don't have identical URLs for the same method). So that wouldn't be an option unless it were opt-in.

There should be no need to disable caching entirely if you are encountering this bug. You can just override getCacheKey() in your Request subclasses to return the method and URL together.

For Volley - perhaps we could change the default cache key to include the method, but only if it is not equal to GET. This should mostly resolve the issue since GET is still distinct from all other request types even if it's not explicitly included in the key, and would also help avoid loss of cached data upon library upgrade in the majority of cases where only GET requests are being cached. The main drawback is that if you previously hit this bug, you may still have data cached from a POST request without the method in the name, and that would cause a mismatch - but you would have gotten this mismatch in this scenario without any change, so it seems no worse than the current world.

**Comment by phearme** [comment]
@jpd236 

> For Volley - perhaps we could change the default cache key to include the method, but only if it is not equal to GET.

it definitely should be changed to include the method in my opinion. not doing so will lead to inconsistent results. in the real world, I see no case where it is normal to GET and POST/PUT/DELETE to the same URL and always expect the same result. really?

**Comment by jpd236** [comment]
Yes, it is absolutely correct that Volley's cache behavior is wrong here. However, we need to balance the need to fix this bug, which impacts a subset of applications, with the fact that a naive fix will cause any existing cache entries to effectively disappear for *all* applications that have already integrated with Volley, regardless of whether they were encountering this problem. That could lead to a substantial latency increase when the app is first reloaded after the update.

**Comment by jpd236** [comment]
So here's where I'm leaning:

- We should turn off caching of POST requests by default. It seems like the wrong thing to do just about all of the time because the request body isn't part of the cache key, so I don't really see how the cache entry could be guaranteed to be valid unless the request body is empty. And generally POST requests are supposed to always go through to the backend. So if you want POST caches, you should be opting in yourself. But I don't want to change default behavior in a bug-fix release, so this will stay as is in 1.1.1, and we'll plan to change it for 1.2.0.

- For 1.1.1, the safest solution I see is what I noted [above](https://github.com/google/volley/issues/154#issuecomment-389243997): edit the default cache key to include the method if it's not equal to GET. Then there is no effect on GET requests; POST requests will continue to be cached, although existing caches will be cleared upon Volley upgrade; and future requests will not collide.
