### ISSUE TITLE
Need feature - Request posting progress callback

### ISSUE THREAD

**Issue by sanoopv3** [google/volley#157]
Hi, 
Please add a new feature .
in Base64 image upload to server using volley. the request is big in size hence while posting , need a posting percentage callback.

Thanks

**Comment by jpd236** [comment]
As noted at: https://developer.android.com/training/volley/index.html

"Volley is not suitable for large download or streaming operations, since Volley holds all responses in memory during parsing. For large download operations, consider using an alternative like DownloadManager."

As such, this request is out of the scope of what Volley can/should do.

**Comment by jpd236** [comment]
(The above comment is about response size, but it applies as well to request size).
