### ISSUE TITLE
Problem with OutdatedLibrary

### ISSUE THREAD

**Issue by EstebanC02** [google/volley#175]
Hi guys, can you help me with this problem!

The problem arose when I updated version to:

`classpath 'com.android.tools.build:gradle:3.2.0-alpha13'. `

![screen shot 2018-04-30 at 2 14 57 pm](https://user-images.githubusercontent.com/11792308/39445605-34f8e170-4c81-11e8-8259-fbb690e96068.png)

**Comment by jpd236** [comment]
Strange! Doesn't seem like something within Volley's control though, rather than an issue with the Android build tools.

Would you mind reporting your issue per the instructions at https://developer.android.com/studio/report-bugs? Be sure to include the details under "Details for build tools and Gradle bugs" when doing so. I think that'll send this to the most appropriate team to take a look.

Thanks :)

**Comment by jpd236** [comment]
(If you do, please link the report here so I can follow along)

**Comment by EstebanC02** [comment]
Sorry, I saw the response until today, the bug was created here: 

https://issuetracker.google.com/u/1/issues/79219523

**Comment by joebowbeerxealth** [comment]
The recommended version (which fixes some recurring crashes) is an unreleased snapshot, right? Could that have something to do with the way this is reported?
