### ISSUE TITLE
compile failed , help pls. 

### ISSUE THREAD

**Issue by kingofswing** [google/volley#180]
implementation 'com.android.volley:volley:1.1.0'

Program type already present: com.android.volley.Cache$Entry
Message{kind=ERROR, text=Program type already present: com.android.volley.Cache$Entry, sources=[Unknown source file], tool name=Optional.of(D8)}

previously I used version 1.0.9.jar in local libs folder.  but after uprade to AS 3.1.2(now the version), It seems there is some thing wrong with volley  or  I did sth wrong, It's ok when under AS 2.x.x . any help would be greatly appreciated!

**Comment by jpd236** [comment]
In general that kind of error implies that there are two copies of Volley somewhere in your build path. Did you remove the .jar from your local libs folder when you added the dependency on 1.1.0? Does `./gradlew dependencies` show anything unexpected?

I'm closing this out as there isn't enough information here for us to reproduce this, but if that's not enough to get you unstuck, you can provide a small sample project that reproduces the issue here and we can take a closer look.

**Comment by kingofswing** [comment]
thanks Mr. Davidson。 Just as you suggested， I found a jar named library-1.0.19.jar in libs folder, deleted. it's ok now.
