### ISSUE TITLE
`./gradlew googleJavaFormat` breaks method chaining if line fits on one line

### ISSUE THREAD

**Issue by dylan-chong** [google/volley#182]
Diff of before and after running format:

```diff
-        JSONObject jsonObject =
-                new JSONObject()
-                        .put("first-key", "first-value")
-                        .put("second key", 3);
+        JSONObject jsonObject =
+                new JSONObject().put("first-key", "first-value").put("second key", 3);
```

This is rather annoying (especially when the chained calls reach exactly 99 characters. You get an unnecessarily long line

Is this intentional?

**Comment by jpd236** [comment]
This is probably more a question for the [google-java-format](https://github.com/google/google-java-format) project.

But at a high level - yes, there will be times that the formatter does something that may not look perfectly ideal in every situation, but in the majority of cases it produces reasonable-looking code. It saves us a lot of time when writing or discussing code to have one tool-enforced set of formatting rules rather than leaving it up to subjective discussions.

For example, you feel the code is cleaner as you formatted it; others might feel it takes up more lines of code than is needed. We could either spend multiple cycles debating this in a code review, or we could let the tool make the decision and move on.

So we and other projects using google-java-format have decided this tradeoff is worth it. You're free to make your own decisions in other projects, but that's the idea behind it. If you feel like there's a general rule here that google-java-format should handle differently that is an improvement across the board, then they might be receptive to it there.
