### ISSUE TITLE
Volley Sending Data twice. 

### ISSUE THREAD

**Issue by Pronoy999** [google/volley#216]
I am sending data to a python server but the python wont send anything back, hence Volley is getting in error response, but its retrying. I dont want it retry anymore. I have tried to set custom retry policy. It doesn't work. Please make a provision to stop this and also give an option to stop retry automatically for any case. 
![screen shot 2018-08-19 at 23 17 55](https://user-images.githubusercontent.com/18458807/44311491-24dca880-a406-11e8-848f-db893888a6d9.png)

**Comment by jpd236** [comment]
If you're seeing four retries, it's not coming from Volley. Depending on whether the response has content or not, BasicNetwork will either throw a ServerError immediately or else call the default retry policy, which has a maximum of two tries. Four tries would imply that whatever is causing these retries is specific to your app or how you're invoking Volley.

So I don't suspect a Volley bug here, but if you feel otherwise, then we will need more information - in particular, the fastest way to get an answer is to provide a small sample app that exhibits the issue.

**Comment by jpd236** [comment]
Note too that the fourth entry in those logs is coming from a different thread altogether (1078 vs. 1077), which is more of an indication that something higher-level than Volley is invoking retries.
