### ISSUE TITLE
onResponse byte

### ISSUE THREAD

**Issue by PascalTang** [google/volley#219]
HI . 
I want to implement a test speed features. 

I have 2 file on backend.
its different size.
I access with onResponse(byte[] response)
I would like to know when I got response byte.
Is it response time is already read all file?
Mean I can just compared response time and no need to do anything else?

**Comment by jpd236** [comment]
onResponse is called when the entire response is read. If you're looking for the time to the first byte, Volley doesn't expose such an API, so you'd need to build an HttpStack which supports this and use it directly.

Personally, I would advise against using Volley for this kind of thing. Most of Volley's strengths involve making the HTTP request lifecycle simpler and giving a nice structure for dealing with background/UI threads and parsing responses. It may impose artificial restraints like the number of threads in the network pool. For a speed test, you don't really care about any of that, but you do want to reduce as much overhead as you can so that you're specifically testing the connection and no other factors. So for this kind of thing, I'd think you should just use an HTTP API more directly.
