### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by amalive** [google/volley#234]
Sometimes when I'm using mobile data to call web service, I got this response " **javax.net.ssl.SSLException: Read error: ssl=0x7927b3df00: I/O error during system call, Connection reset by peer**". While at the same time I test using other library (OkHttp), the service received good. it is caused by what problem?

Thanks for your help 😄

**Comment by jpd236** [comment]
Seems like an error in the underlying HTTP stack you're using (either Apache HTTP or HttpUrlConnection) rather than something in what Volley adds on top of those. And likely just a transient networking issue that a retry would resolve (since you say sometimes).

Perhaps if OkHttp is working well for you, you could try using an implementation of HttpStack based on OkHttp - if I search around it seems like there are a few out there.

You can try using HttpUrlConnection or ApacheHTTP directly to see if you can reproduce the issue without Volley involved and then raise an Android platform bug if there's a specific issue. You might also try adjusting your Volley retry policy to try again in the event of a transient flake, which may very well be what OkHttp is doing underneath the covers.
