### ISSUE TITLE
Volley Not Communication with Localhost API, while Server on cloud

### ISSUE THREAD

**Issue by muhammad-fahd** [google/volley#236]
I was trying to connect with my locally hosted API (Note: Database on Azure). but I got the error response like `NoConnectionError, ConnectionException: Failed to connect to localhost or 127.0.0.1:52479`.

but my provided URL get the data from the server if I access it from the browser.
here is code.

`StringRequest request = new StringRequest(CommonTask.URL_Doc, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                textView.setText("Response : " + response);
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                textView.setText("Ërror : " + error.toString());
            }
        });
        SingltonPattren.getInstance(getApplicationContext()).addToRequestQueue(request);`

**Comment by jpd236** [comment]
Unlikely to be a specific issue to Volley. Can you try using a simpler class like HttpUrlConnection to see if you can reproduce the issue? Maybe your app is missing the INTERNET permission, or the request is otherwise not identical to what you're loading in the browser. (Or there are proxy settings involved or some other difference).
