### ISSUE TITLE
No Streaming support!?

### ISSUE THREAD

**Issue by myxibrium** [google/volley#246]
I can't believe that Google still recommends Volley with this enormous missing feature. We built an entire application that relies on the cookie management of Volley, only to find out that we can't upload large files, and we can't implement loading bars! Not only that, but it seems like the developers are totally OK with this, saying it's "not in the spirit of Volley."

It's time for you to acknowledge this missing feature and provide a workaround!

**Comment by jpd236** [comment]
I am sorry that you ended up in this situation and if it wasn't clear from the get-go that this isn't a suitable use case for Volley. There's more context at our [FAQ](https://github.com/google/volley/issues/246) as to why this isn't just a "missing feature", but something fundamentally different in architecture from how Volley was built and thus not something we can support.

The official docs at https://developer.android.com/training/volley/ also note this:

"Volley is not suitable for large download or streaming operations, since Volley holds all responses in memory during parsing. For large download operations, consider using an alternative like DownloadManager."

I'm not sure there's much more we could have done to make this limitation clearer up front, but please let me know if there is any other place that should mention it.

**Comment by myxibrium** [comment]
It would be nice to offer an alternative for streaming uploads.

**Comment by tmm1** [comment]
There's a fork of Volley with a patch that provides the underlying inputStream, which can be fed into streaming json parsers etc. It would be nice to be able to use such an API without having to maintain a fork or use someone else's 4 year old copy.

https://github.com/fleficher/android-better-volley/commit/40997a357dd2febfe24a1178e2fbaa94ba995bbf

**Comment by jpd236** [comment]
If responses are small and you just want to use a parsing API that takes an InputStream but not a byte[], you can use ByteArrayInputStream to wrap the byte[] response contents in an InputStream.

If responses are large, then this isn't a problem that can be addressed just by exposing a raw InputStream. It is fundamental to Volley's operation that response bodies can fit in memory.

**Comment by tmm1** [comment]
Okay thanks. My responses are generally small, but it appears they have grown slightly in the past three years as my application and API have been enhanced, and now they are too large for certain devices with low memory to be able to load without an OOM.

I will switch to another http client better suited to this purpose.
