### ISSUE TITLE
Volley is using TCP / UDP ?

### ISSUE THREAD

**Issue by wirmanto** [google/volley#253]
Volley is using TCP or UDP ? if TCP, how many bytes in their header, where can we look at, how many bytes in their payload, and their trailer. same for UDP, where can we look at.

**Comment by jpd236** [comment]
Volley is generally unaware of the underlying network technology, but as far as I know the two network stacks bundled with it, based on HttpUrlConnection and Apache HTTP, both only support TCP connections.

The other questions depend entirely on the request/response. I don't think these are questions we can generally answer for you here, as this is a bug tracker for Volley, and I think you'd have better luck asking your question on a more general forum like StackOverflow, but please let me know if there's an issue you're reporting with Volley, or a concrete feature request that you're making and we can take a look.

**Comment by dot3kse** [comment]
okay i get it. sorry for asking here, because i don't know where to ask since it does not come with network packet explained. i had to ask because i'm using volley and i need to explain what i'am using in my project. i mean when we sent request, i read there are some default header TCP connection that i can't explain with, like this image. so what am i get at is, there is no standard default header for TCP connection with volley. thanks for your reply.
![default header](https://user-images.githubusercontent.com/46005485/50239611-44f09880-03f5-11e9-9a8a-7398ee7d8026.png)
