### ISSUE TITLE
BasicNetwork.performRequest Error only on some devices

### ISSUE THREAD

**Issue by yasandev** [google/volley#271]
I am getting this error log on only a low percentage of my users:

`com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:181)
com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) `

This caused Volley not be able to load the JSON file I am requesting which makes the app unusable.

This is my request code:

` final JsonArrayRequest request = new JsonArrayRequest(Request.Method.GET, url, null,
                response -> {
//Getting info from the response json
}`

**Comment by jpd236** [comment]
Line 181 of BasicNetwork is:

https://github.com/google/volley/blob/d1a3d5388c79ff1a6fdb904daeff9b39d0bb7d26/src/main/java/com/android/volley/toolbox/BasicNetwork.java#L181

```throw new NoConnectionError(e);```

which happens if the underlying HTTP stack throws an IOException when making the request and we do not get an HTTP response back. As implied by the error name (which I'm not sure why it's omitted in this report - is that the full stack trace?), this generally means that the user does not have connectivity.

This seems like a reasonable failure. Some percentage of the time, the HTTP call fails to go through, and you get a no connection error as a result. There's no bug - the network is just not 100% reliable. Even if you checked for connectivity up front, the state could change between your check and when you make the request, and naturally one server might be available when another isn't.

Your app would need to handle the possibility of a NoConnectionError or other transient failures over the network and fail gracefully by indicating that the user has no connectivity, and perhaps offering them the ability to retry.

**Comment by yasandev** [comment]
I have users with 2 devices that the app works fine for them on one and doesn't work at all (due to this error) on the other one. It's like the app cannot access my host on some of the devices somehow (while it can access Admob and OneSignal). I am just really clueless about what this might be caused by and I am trying to find what I should "fix".

**Comment by jpd236** [comment]
If you have a user who can consistently reproduce an issue and otherwise has connectivity, you might try eliminating Volley from the equation by just using a simpler API like HttpUrlConnection. If you can reproduce the problem there, it's not a Volley issue, but just an issue with that device not being able to reach your server.

**Comment by madmaxhasan** [comment]
Can you help me out with this error

`com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:205)`

It shows `throw new ServerError(networkResponse);`

I don't have any clue about it.
