### ISSUE TITLE
Gzip requests with volley

### ISSUE THREAD

**Issue by KevKo1990** [google/volley#284]
As the title tells, I am not completely sure about the usage of gzip for requests in volley. I understand that the underlying network stack can support gzip for responses, however I don't understand what happens if I want to send a gzipped JSON request to a server?

https://developer.android.com/reference/java/net/HttpURLConnection talks in its documentation only about responses as well.

Would I have to implement a custom request class to use a gzip compressed request?
(e.g. by extending the StringRequest class?)

**Comment by jpd236** [comment]
Yes, I think you'd need to do this manually. You already need to extend the StringRequest class if you want to set a request body by overriding getBody (which is the thing you'd be compressing in the first place). I think you would need to manually compress the body contents and also set the Content-Encoding header to gzip (by overriding getHeaders).

If you're sending requests that are so large that they benefit from compression, you may want to consider another approach than using Volley, because Volley is meant for small requests and responses - it stores all of them in memory and does not support partial uploads/downloads for a simpler API. If your requests are not that large, then is there really a benefit from compressing them?
