### ISSUE TITLE
source code question

### ISSUE THREAD

**Issue by dan6886** [google/volley#285]
in the  \volley\src\main\java\com\android\volley\NetworkDispatcher.java
 public void run() {
  line:144              request.markDelivered();
  line:145              mDelivery.postResponse(request, response);
}

the request post by the mDelivery will call markDelivered in postResponse() as below .**i want to confirm if the line 144  is unnecessary?** thanks 

public void postResponse(Request<?> request, Response<?> response, Runnable runnable){
        request.markDelivered();
        request.addMarker("post-response");
        mResponsePoster.execute(new ResponseDeliveryRunnable(request, response, runnable));
}

**Comment by dan6886** [comment]
may be there is another  class XXXDelivery  implements ResponseDelivery，and the user may forget to markDelivered in the override code, right?

**Comment by jpd236** [comment]
Yeah, these do seem redundant technically when using both ExecutorResponseDelivery and NetworkDispatcher, but as you note, if you have a custom delivery, this helps ensure the request gets marked as delivered. There's no harm in the method being called twice since it's just flipping a bit.

FWIW both of these markDelivered calls have been present since the [original Volley commit](https://android.googlesource.com/platform/frameworks/support/+/3713094c56d25e25df2a508dbee4aea869ffdea1).
