### ISSUE TITLE
is it working with synchronous mode or asynchronous mode?

### ISSUE THREAD

**Issue by jackzhp** [google/volley#291]
can anyone tell the http request is in synchronous mode or asynchronous mode?

thanks.

**Comment by jackzhp** [comment]
must  be in synchronous mode. for asynchronous mode, use Cronet instead.

**Comment by jpd236** [comment]
The app-facing API for making requests is asynchronous. You add requests to the queue and the provided response listener will be invoked when the request completes.

Some of Volley's internals are synchronous when it comes to dispatching the requests, but for most applications this would not be a major concern. If you are dispatching many parallel requests or are severely memory constrained then Volley's design may not be ideal because it spawns a few threads for cache and network dispatching that never stop themselves. Fixing that is tracked by https://github.com/google/volley/issues/181, but from the app's perspective this shouldn't result in any changes to the API surface unless you're making custom HTTP stacks or cache implementations.
