### ISSUE TITLE
Common error threatment for all volley requests

### ISSUE THREAD

**Issue by iang-br** [google/volley#305]
I have an android app that makes up to 30 requests to a web API using Volley.

I need to add a threatment for all times that an API returns error code 422 (AuthFailureError): go to login screen.

I don't want to change all 30 requests to do so.

Is there a way of overriding all request error threatments only once?

**Comment by jpd236** [comment]
The typical pattern that I've seen for something like this is to use a base Request class that all of your requests can extend. This would require a one-time change to have all your requests extend this class, but from there you have all the error handling logic in a single place, and could make future changes to the common logic without needing to touch each and every request.

If you have a common RetryPolicy, you might also be able to hack something up there, but I'm not sure how well that would work - for example, if you notice an auth error, you could start the login screen from an attached activity and block until the login completes. And you could also explore extending BasicNetwork and overriding performRequest, although it's not particularly well-built for subclassing.

But I think you'll net out to a cleaner implementation overall if you move the common handling one level higher - into common logic in your activities/fragments. This is a more appropriate home IMHO because launching activities directly from Volley is too low level - suppose at some point you add a background request to your application where the appropriate resolution might be to show a notification to resolve the issue rather than pop up a random login screen over whatever the user happens to be doing elsewhere. On the other hand, if all your activities/fragments extend a common base class or otherwise have common scaffolding to handle Volley requests, you can put logic to handle AuthFailureErrors by launching the login screen there in coordination with whatever else the user might be doing in the app.
