### ISSUE TITLE
Android Volley Returning results twice for one request If used cache

### ISSUE THREAD

**Issue by vijayideas** [google/volley#316]
Check full [question](https://stackoverflow.com/questions/59784726/android-volley-returning-results-twice-for-one-request-if-used-cache)

**Comment by jpd236** [comment]
Your question links through to https://stackoverflow.com/questions/20027995/android-volley-returning-results-twice-for-one-request/20040402#20040402 which explains that this is due to soft TTL support, and is working as intended. When a request is considered expired according to the soft TTL, you'll potentially get the response delivered twice - once from the cache entry, and then once again from over the network with the refreshed data.

If you don't want this behavior, then adjust your server's response headers. For you to have a different soft TTL and hard TTL (after which the cache entry will not be used), your server must be returning a response with a Cache-Control header including either "must-revalidate" or "proxy-revalidate" and a positive "stale-while-revalidate" value. See https://web.dev/stale-while-revalidate/ for more details on why Volley responds to this behavior the way it does.

FWIW, the responses can be distinguished by checking Response#intermediate, which is true for the cache response and false for the final network response.

**Comment by vijayideas** [comment]
@jpd236 , Can you answer [this](https://stackoverflow.com/questions/59786456/how-to-get-refreshed-data-every-time-from-volley-if-network-is-online) ?

**Comment by jpd236** [comment]
Assuming the question is:

"But I want a response from server if the network is online and from cache if the network is offline."

There's no simple solution to this as far as I can tell because the Response#intermediate bit is not propagated back to the response callback. Here are two options that should work, though:

- Attempt the network request with Response#shouldCache set to false to force it to go over the network. If it succeeds, use that data. If it fails, you can fall back to querying your Cache instance directly for the given key (Request#getCacheKey) and use it (if it's not expired, if that's the semantics you want).

- Create your own implementation of ResponseDelivery. You can use that to handle Response#intermediate differently. In particular, what you'd want to do is to hold any intermediate responses for a request until you get the final response; if the final response is successful, you discard the intermediate result and use the final one; if it's not, and you have a valid intermediate result, you can use that instead.

In the future, if you have further questions, please use our user group at volley-users@googlegroups.com if you are unable to get help via StackOverflow or other mechanisms. This is for tracking issues with Volley rather than for fielding general questions.
