### ISSUE TITLE
why i am getting out of memory with volley?

### ISSUE THREAD

**Issue by hawad22** [google/volley#319]
when i reach 1300 thread number  its crash by out of memory

how do i clear memory or stop all thread or remove it ?

please

**Comment by jpd236** [comment]
Sorry, there's not enough information here to diagnose what's going on. 1300 threads is a _huge_ number. Are you saying that's how many Volley is starting? Volley should generally only have a few threads - some network dispatchers and a cache dispatcher. If you're seeing more than that from just Volley then there is probably a bug in what you're doing; perhaps you're creating new RequestQueues for each request and leaking them rather than reusing them.

If you think there is a bug in Volley, then please provide more information, e.g. a dump of all the thread states showing that Volley is running lots of threads, and ideally some sample code demonstrating the problem.
