### ISSUE TITLE
Marker exception

### ISSUE THREAD

**Issue by ravirajjak** [google/volley#32]
FATAL EXCEPTION: main Process: in.publicam.cricsquad, PID: 7283
  java.lang.IllegalStateException: Marker added to finished log
  at com.android.volley.VolleyLog$MarkerLog.add(VolleyLog.java:132)
  at com.android.volley.Request.finish(Request.java:240)
  at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:109)

Lenovo a7000 Marshmallow OS

**Comment by jpd236** [comment]
A stack trace alone is not a sufficient crash report. This can happen due to developer error (the same request shouldn't be reused twice).

If you're not the developer of this app please report your crash to the developer.

If you are the developer then please provide more context for what is causing the crash, i.e. sample code.

**Comment by ravirajjak** [comment]
I am not getting at a particular class or a line. it just shows the marker add exception.

**Comment by sauniksingh** [comment]
-dontskipnonpubliclibraryclasses
-dontobfuscate
-forceprocessing
-optimizationpasses 5

-keep class * extends android.app.Activity
-assumenosideeffects class android.util.Log {
public static *** d(...);
public static *** v(...);
}
