### ISSUE TITLE
Volley double post when have slow request

### ISSUE THREAD

**Issue by harishankar-jayasakthi** [google/volley#323]
I have a problem with Volley POST request on slow network. Sometimes my POST request is executed twice or more resulting in multiple (2 or more) postings for 1 request.

 I tried few solutions, but not working
https://stackoverflow.com/questions/60489437/android-volley-double-post-sometime#comment107009216_60489437

Full source code: https://androidkeynotes.blogspot.com/2020/02/volley.html
How to avoid duplicate POST using volley lib?

**Comment by jpd236** [comment]
First of all - you should _strongly_ consider making your client/backend resilient to the possibility that your POST request is executed twice. Even if you accomplish your goal of only having it execute once, it's perfectly possible for the request to appear to have failed on the client side (e.g. time out) when it actually succeeded on the backend. The user is going to then retry and presumably encounter the same failure. So, better to have the client be able to retry repeatedly and have the backend handle the request idempotently than try to make the client request things once on a poor network, which is likely to be the case often on a mobile device. You will have a much easier time building the client and your users will have a better experience.

Anyway, if you want Volley to only try a request once, passing in a DefaultRetryPolicy with the second argument (maxNumRetries) == 0, the request should only be tried once, as long as you're using the default HttpStack (HurlStack). If for some reason you're still using the Apache HTTP stack, that stack might do some inline retries when requests fail to connect.

Can you run "adb shell setprop log.tag.Volley VERBOSE" to enable verbose logging, force stop and restart your app, and then reproduce the problem and provide the logs from Volley when a request happens twice? What device / version of Android are you testing on? I appreciate the sample code, but I'm not sure how to run it since it's just a few of the source files rather than a fully functioning setup.

**Comment by jpd236** [comment]
Can you determine on the server side which devices / Android versions are affected? You should be able to include that information with requests, if you aren't already. That might help narrow the scope of the question if it only impacts certain versions of Android /  certain devices.

From the threads you linked, it might be a bug with HttpUrlConnection in some situations. You can always extend HurlStack and override createConnection to try some of the workarounds provided in those links (like calling setChunkedStreamingMode(0)). If we were able to identify a set of devices or other circumstances where that was necessary, we could consider including that in Volley itself.

You might also consider trying another HTTP stack to see if that works for you. Volley doesn't provide any official ones at the moment, but there are many floating around for things like OkHttp or Cronet.

Without more information I'm afraid there's not much more we can dig into from our side. Please feel free to provide more details as suggested above or a clearer reproduction case, and we can take a closer look.
