### ISSUE TITLE
Make Request.deliverResponse() public to ease unit testing

### ISSUE THREAD

**Issue by minas1** [google/volley#326]
`deliverResponse(T response)` is protected, which makes unit testing requests a pain. Right now I have to:

1. Extend the request and redefine `deliverResponse()` as public.
2. Inject a factory in my classes that create the requests so that my own implementation is returned.
3. Call `deliverResponse()` of my own Request class from the unit test.

This adds noise to my code which would not exist had `deliverResponse()` been **public**.

`deliverError(VolleyError error)` is public by the way. I see no reason why `deliverResponse()` shouldn't be.

**Comment by jpd236** [comment]
I'm a little unsure why it's necessary. Protected visibility implies package visibility, and generally a unit test for a Request subclass would be in the same package as the Request itself. Thus, a unit test for a request should have no problem calling deliverResponse for that request.

I don't really follow what you're doing in your code. You must have a subclass of Request already to be able to set deliverResponse to something that's not abstract, so whatever is creating your requests already needs to be aware of these custom Request classes. Can you explain in further detail what you're doing and/or provide some sample code demonstrating the problem?

Note that we cannot safely make this change without a major version increase, because existing Request subclasses are in the wild which declare protected access on deliverResponse, which means increasing the base class visibility to public would break the build for those applications.
