### ISSUE TITLE
Invoke RetryPolicy (on an opt-in basis) for NoConnectionErrors

### ISSUE THREAD

**Issue by rtinku** [google/volley#332]

**Comment by jpd236** [comment]
I'm not really sure what you're asking here. OnConnectionException isn't anything I've heard of.  In general you can call Request#setRetryPolicy to provide a RetryPolicy implementation which will retry requests however you see fit.

In the future, if you have further questions, please use our user group at volley-users@googlegroups.com if you are unable to get help via StackOverflow or other mechanisms. This is for tracking issues with Volley rather than for fielding general questions.

**Comment by rtinku** [comment]
> I'm not really sure what you're asking here. OnConnectionException isn't anything I've heard of.  In general you can call Request#setRetryPolicy to provide a RetryPolicy implementation which will retry requests however you see fit.
> In the future, if you have further questions, please use our user group at volley-users@googlegroups.com if you are unable to get help via StackOverflow or other mechanisms. This is for tracking issues with Volley rather than for fielding general questions.

sorry it's my mistake  not 'OnConnectionException' , it's NoConnectionError.
I want to perform request retry on 'NoConnectionError'. if any solution is available please provide it.

**Comment by jpd236** [comment]
Got it. You're right that we don't currently retry these - the assumption has been that if there's no connection available on the device, then there's no point in retrying again immediately, and you'll need to wait until a connection comes back up.

I'm open to a change in Volley to allow controlling this behavior and asking the RetryPolicy to decide what to do rather than assuming we shouldn't retry. https://github.com/google/volley/issues/48 has some discussion on what a PR to fix this would look like.
