### ISSUE TITLE
getting HTML responce while using volley POST method

### ISSUE THREAD

**Issue by Ashish2000L** [google/volley#354]
Using volley dependency :

> implementation 'com.android.volley:volley:1.1.1

> implementation 'androidx.appcompat:appcompat:1.1.0'

I am using url like: 

> http://mywebsite.com/myfile.php

I am expecting my php file to return '0' or '1' as a response, but i am getting 

><html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("e30dc905aac0f82aa2929e65e9758033");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://free4all.ezyro.com/music_streaming/register.php?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

i don't how to enable the javascript by using volley if it is possible?

i have added android:networkSecurityConfig="@xml/network_security_config" to my manifest.xml file.
Please let me if you need more information regarding this problem.

**Comment by jpd236** [comment]
This sounds like an issue with your server returning unexpected HTML responses, or with you not configuring your request in a way that your server expects. It's very unlikely to be an issue with Volley itself.

My suggestion for you would be to try making the request with the HTTPUrlConnection class directly (see https://developer.android.com/reference/java/net/HttpURLConnection). Since Volley is just doing this under the covers, it's very likely you'll see exactly the same result, in which case this is clearly not a Volley issue. If you get the result you expect, then feel free to reopen with more details.
