### ISSUE TITLE
Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by Ashish2000L** [google/volley#355]
> implementation 'androidx.appcompat:appcompat:1.1.0'
> implementation 'com.android.volley:volley:1.1.1'

I am using post method to send data the server but i got this error

> onErrorResponse: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by jpd236** [comment]
Volley isn't doing anything special here regarding SSL. I recommend trying to reproduce your problem with whatever HTTP stack you're using under the covers (e.g. HttpURLRequest); you'll likely encounter the same problem.

Based on a quick search, it seems like a legitimate error because the server you're trying to connect to isn't presenting a valid certificate. You'll have to fix the server.
