### ISSUE TITLE
OutOfMemoryError: Failed to allocate a 24 byte allocation with 2411288 free bytes and 2354KB until OOM

### ISSUE THREAD

**Issue by histone** [google/volley#390]
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2411288 free bytes and 2354KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 187957248 bytes)

java.lang.StringFactory.newStringFromString StringFactory.java
org.json.JSONTokener.nextString JSONTokener.java:214
org.json.JSONTokener.nextValue JSONTokener.java:111
org.json.JSONTokener.readObject JSONTokener.java:371
org.json.JSONTokener.nextValue JSONTokener.java:104
org.json.JSONTokener.readArray JSONTokener.java:440
org.json.JSONTokener.nextValue JSONTokener.java:107
org.json.JSONTokener.readObject JSONTokener.java:394
org.json.JSONTokener.nextValue JSONTokener.java:104
org.json.JSONTokener.readArray JSONTokener.java:440
org.json.JSONTokener.nextValue JSONTokener.java:107
org.json.JSONTokener.readObject JSONTokener.java:394
org.json.JSONTokener.nextValue JSONTokener.java:104
org.json.JSONTokener.readObject JSONTokener.java:394
org.json.JSONTokener.nextValue JSONTokener.java:104
org.json.JSONObject.<init> JSONObject.java:164
org.json.JSONObject.<init> JSONObject.java:181
com.android.volley.toolbox.JsonObjectRequest.parseNetworkResponse JsonObjectRequest.java:85

**Comment by jpd236** [comment]
It's pretty unlikely that Volley is the source of this crash. (If there were an actual Volley memory leak, we'd have heard more about it by now). The crash happens to be occurring in Volley, but it's likely due to something specific in your application.

Some possibilities include:

1) You are attempting to parse a large response - that would correspond with the stack trace you're seeing in trying to parse some JSON. Volley is not well-suited to large responses because it keeps the entire response body in memory. How big are your responses?

2) You have a memory leak elsewhere in your app and this happens to be the allocation that causes it to run out. One common problem when using Volley is creating RequestQueues for each request rather than one global process-level RequestQueue, which can leak threads. But the memory usage could be happening elsewhere.

I'd recommend investigating along those two avenues. If you have a consistent repro case that can be isolated into a small sample application and the response sizes are reasonably small (less than ~1 MiB), feel free to reopen with more details.
