### ISSUE TITLE
Generic typed RequestEventListener ?

### ISSUE THREAD

**Issue by RobbWatershed** [google/volley#403]
Hi everyone and thanks for the long due update !

So `RequestFinishedListener` has been replaced by `RequestEventListener`. Fair enough.

But why wasn't `RequestEventListener` typed ? Having to deal with `Request<?>` looks dirtier to me than using generic typed `RequestFinishedListener<T>`, producing `Request<T>`, which was neat.

Any reason for that ?

**Comment by jpd236** [comment]
What's dirty about `Request<?>`?

It's an accurate type, because any kind of Request can be submitted to the RequestQueue at any time, so there's no guarantee of any particular kind of Request that is passed to the callback. If you specified a specific type and actually depended on that type in your code, then it would almost certainly crash at runtime if another type of request were ever used, without any indication of something going wrong at compile time.

That being said, I don't see any methods (outside of compareTo) in Request's public-facing interface that actually depends on the type, so I don't see a practical reason why you'd need a type.

All in all, the wildcard seems like exactly the right type to be using here for accuracy, and I'm not seeing what would be problematic about it, but let me know if I've missed a use case here.
