### ISSUE TITLE
I found the volley we used through git records. How can i find which version of volley is the place selected in the red box?

### ISSUE THREAD

**Issue by creativityingenuity** [google/volley#427]
![image](https://user-images.githubusercontent.com/12170093/130769919-2cb481b7-c23e-4858-83c8-4fc06966ff17.png)

**Comment by jpd236** [comment]
The first official Volley binary release, 1.0.0, is from this commit: https://github.com/google/volley/releases/tag/1.0.0.

There was no official release at the [commit](https://github.com/google/volley/commit/8c5daf39f32ed5ed4e5dc8aa78cbcf5e169c3e4e) you highlighted (though it was included as part of that release).

I'm not really sure what problem you're trying to solve here. We haven't made significant backwards-incompatible changes to Volley in a long time, so your app should have no issues with moving to the latest release - I'm not sure why you'd want to use a version that's 8+ years old. If the latest version isn't working for you, please let us know why.

If you have future questions (rather than issue reports / feature requests), I would recommend another channel like our Google Group volley-users@googlegroups.com or Stack Overflow - this is an issue tracker to report problems with Volley rather than a general question forum.
