### ISSUE TITLE
Release old version 1.1.1 to google repository?

### ISSUE THREAD

**Issue by AnmAtAnm** [google/volley#428]
A few libraries still reference the old version of Volley (I'm looking at Google's Places API, in particular). With jcenter()/Bintray going down (gone down?) can someone place push the older version(s) to google's repo?

**Comment by jpd236** [comment]
Unfortunately, no - Google's repo (and Maven Central) have stricter requirements around acceptable artifacts which Volley 1.1.1 didn't meet. See https://github.com/google/volley/issues/394#issuecomment-783714765 for more details.

Note that if you're using Gradle, the fact that a library you're using depends on v1.1.1 can be worked around by depending on a newer version of Volley in your own application, since Gradle will resolve dependencies by picking the newest version (see https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:resolution-strategy).

**Comment by lmj0011** [comment]
The only workaround seems to restricting jcenter to only allowing the volley package

add this to your Project's build.gradle

```gradle
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() {
            content {
                includeModule("com.android.volley", "volley")
            }
        }
    }
}
```

ref: https://jeroenmols.com/blog/2021/02/04/migratingjcenter/
