### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by ofarril870616** [google/volley#430]
I am running app in android 11, api level 30, android volley answer me object null and the app close. I am using 1.2.1 version of android volley.

**Comment by jpd236** [comment]
Hi there,

There aren't enough details here for this bug to be actionable. Sounds like maybe you have a null pointer exception in your application code, but Volley is unexpectedly returning null somewhere you don't expect? If so, where?

If you'd like more help, I'd recommend providing some sample code and more detail about which of your expectations is not being met by Volley, and we can take a closer look. You might also have a better time using a more general help venue like our Google Group (volley-users@googlegroups.com) or StackOverflow, since it is more likely to be an issue with your application rather than a bug in Volley itself.
