### ISSUE TITLE
Type com.android.volley.Cache$Entry is defined multiple times

### ISSUE THREAD

**Issue by soryaphoeun** [google/volley#434]
Hi team, I have faced this issue when I was implementing the Volley library both in the root project and SDK.

Type com.android.volley.Cache$Entry is defined multiple times

Please help. Thank you

**Comment by jpd236** [comment]
Typically, this happens due to an issue with your dependencies. You and/or another library your app depends on are depending on two different instances of Volley which both contain this class, e.g. Volley from Maven Central and also a prebuilt JAR that contains the class, or Volley and a fork of Volley which didn't rename the packages. You can typically track this down by looking into the full list of dependencies in your build (e.g. for [Gradle](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html)) and reconciling conflicts.

Beyond that, there's not enough information here to provide more help. If you'd like more guidance, please attach a small sample project that would allow us to reproduce the issue.
