### ISSUE TITLE
Volley: [5311] NetworkUtility.logSlowRequests: HTTP response for request=<[ ]

### ISSUE THREAD

**Issue by PanneerJan2** [google/volley#443]
I Tried Many APIs and I'm getting NetworkUtility.logSlowRequests Warning and sometimes API Fails.
I have Tried Increasing TimeOut Seconds and Increased Max Retries and Still i'm getting this warning 
 Val queue = Volley.newRequestQueue(applicationContext)

 val socketTimeOut = 30000
        val jsonObjectRequest = JsonObjectRequest(Request.Method.POST,url,jsonObject,{res->
            
        },{error->
            
        })
        val policy: RetryPolicy = DefaultRetryPolicy(
            socketTimeOut ,
            DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
            DefaultRetryPolicy.DEFAULT_BACKOFF_MULT
        )
        jsonObjectRequest.setRetryPolicy(policy)
        queue.add(jsonObjectRequest)
Warning -> 

Volley: [3288] NetworkUtility.logSlowRequests: HTTP response for request=<[ ] https://www.google.com 0xd61ac103 NORMAL 1> [lifetime=6260], [size=159369], [rc=200], [retryCount=1]

**Comment by PanneerJan2** [comment]
This Warning occurs in OS <=10 Not for OS > 10

**Comment by PanneerJan2** [comment]
Still I'm Facing Same Issue

**Comment by jpd236** [comment]
(More details in https://github.com/google/volley/issues/444 - you can add further comments here rather than opening new issues)

One thing to note is that when this warning is logged, the requests are actually failing once (presumably a timeout) and then succeeding on the second try, since retryCount = 1. This is a little strange, in that if you're setting the timeout to 30000ms, it would seem it shouldn't be failing so quickly, although timeouts are a bit strange with HttpURLConnection and don't always work as you'd expect. Are you setting any timeouts on the HttpURLConnection? What happens if you do setConnectTimeout(30000) and setReadTimeout(30000) on the connection to match what Volley is doing with your retry policy?

It might also help to enable debug logging by running `adb shell setprop log.tag.Volley VERBOSE` and then force-stopping/restarting your app. This should add adb logging indicating each part of the request lifecycle, including any intermediate failures.
