### ISSUE TITLE
Volley request not working over mobile data network (3G and 4G)

### ISSUE THREAD

**Issue by felipheggaliza** [google/volley#59]
I am getting this error when making a POST request when connected to mobile data network:

{"statusCode":"com.android.volley.NoConnectionError: java.net.SocketException: socket failed: errno 64 (Machine is not on the network)"}

**Comment by jpd236** [comment]
The underlying HTTP stack is failing to connect to the server. It could be an issue with the mobile network not actually providing connectivity to the site in question, or the site itself being down.

I would suggest trying a simple HttpUrlConnection and seeing if it works to the same endpoint, as this seems very unlikely to be an issue in Volley specifically.

If you have further troubles I might suggest trying the volley-users@googlegroups.com usergroup or a site like StackOverflow as this site is for tracking bugs in Volley.

**Comment by felipheggaliza** [comment]
I am switching from Wifi to Mobile data, and it seems that Volley is using the same old socket to make the new request. For example: The app was online using wifi, but when the app switches to mobile data, volley is attempting to send request using that "wifi socket".  

I am trying to catch this error and force volley to use a new socket. Do you how can I do socket renew on Volley?

**Comment by jpd236** [comment]
Are you seeing this failure on requests that are started fresh after changing the network?

I did notice a user hitting this issue in https://stackoverflow.com/questions/38572938/android-network-not-reconnecting-when-wifi-drops because they hardcoded a process-wide default network to one value and didn't update it to another. Are you doing anything with ConnectivityManager/Network objects in your app? Do you have sample code you can provide and steps to reproduce the problem?

In general I believe things should be working fine by default in that if you switch from Wi-Fi to mobile data, future requests (those queued after the switch is complete) should go over mobile data with no problems.
