### ISSUE TITLE
OS < Android 4.4 doesn't work with TLS 1.2

### ISSUE THREAD

**Issue by yakdere** [google/volley#77]
Details from Mihai Petresco : @mihaicristianpetrescu
I've managed to build an app that fixes the issue for both devices that have/don't have Google Play Services installed.
The fix in our case has forced us to enable TLS v1.1 on our backend server because by using only TLS v1.2 no matter what fix I've tried it wasn't working.
With TLS v1.1 enabled, on devices that run Android 4.4, API calls get through with the fix in place. Without it they don't. You can try it out yourself by using an emulator with Android 4.4 and no Google Play Services installed. If we then disable TLS v1.1 and leave just TLS v1.2 it doesn't work anymore:

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8765850: Failure in SSL library, usually a protocol error

If there is any way of getting it to work with having only TLS v1.2 enabled on the backend API server and a workaround for older Android running devices, that would be great and ideal, because SSLv3, TLS v1 and TLS v1.1 are not recommended to be used on a secure server. I understood that with the proper implementation TLS v1.1 could be used but still, it would be great to have only TLS v1.2 for all our users.
The sample app is attached. 
[SSLTLSTestApp.zip](https://github.com/google/volley/files/1252695/SSLTLSTestApp.zip)

**Comment by jpd236** [comment]
The sample code you provided does not appear to use Volley. It sounds like you have a generic Android issue in which case this is unfortunately not the right issue tracker to use. This is an issue tracker for the Volley library.

**Comment by yakdere** [comment]
@jpd236  Thanks for looking into this bug. We are using Volley although the sample code doesn't use it. As you have mentioned this is not directly a Volley issue, but we have recommended to report the issue here. I would like to know if there is a support can be provided by Volley or maybe there is already a workaround written by the team in order to test Volley on devices running Android OS 4.4 and lower. Also I would appreciate if you could direct us to the right repo/team? FYI @mihaicristianpetrescu

**Comment by jpd236** [comment]
I'm afraid I'm not personally aware of any workarounds. I would certainly consider a pull request that adjusted the behavior of whichever HttpStack is affected (seems like HurlStack based on the stack trace but not sure).

Based on a quick search it seems likely that you'd need to override certain properties on HttpUrlConnection to configure it to use TLSv1.2 (ref: https://groups.google.com/forum/#!topic/android-security-discuss/-A84BBtN20g). If that resolves the issue, you can always extend HurlStack and override createConnection to apply those overrides in Volley.

**Comment by savasadar** [comment]
https://stackoverflow.com/a/33874126/793880

**Comment by jpd236** [comment]
Thanks. Will look more closely into the implications of that hack to see if it's reasonable to put in Volley proper, or if it brings unacceptable risk along with it.

**Comment by jpd236** [comment]
I looked more closely at this issue. It is indeed the case per SSLSocket's Javadoc that TLSv1.1 and v1.2 are generally supported but off by default on API 16-19 devices.

[OkHttp appears to have adopted the policy](https://github.com/square/okhttp/issues/2259) that only the system default TLS versions should be used, and I'm hesitant to have Volley run counter to that. It seems all too possible that there would be some kind of bug or limitation in the TLSv1.1 or 1.2 implementations on these (legacy) devices that could impact servers that do support TLSv1.0. So it seems too risky to change the default in Volley.

My personal recommendation for anyone encountering this issue would be:

- If you already depend on Google Play Services or don't mind taking on that dependency, use [ProviderInstaller](https://developer.android.com/training/articles/security-gms-provider.html) to install a new SSL provider. This provider will have TLSv1.2 enabled by default and is generally preferable to any legacy platform provider as it will always have the latest updates.

- Otherwise, HurlStack has a constructor which takes a custom SSLSocketFactory; you may provide one on API 16-19 devices which adds TLS v1.1 and v1.2 to the enabled protocols for any socket it creates. You can look at #137 for an example of how to do this; although I've decided not to merge this into Volley at this time, it should be straightforward enough to copy the classes here and/or adapt them to your needs.
