### ISSUE TITLE
Add the GsonRequest

### ISSUE THREAD

**Issue by Hemaolle** [google/volley#84]
The Android training site contains a sample for a GsonRequest that uses Gson to parse a JSON reponse to Java objects: https://developer.android.com/training/volley/request-custom.html, but it's lacking at least the support for POST requests. Also feels silly for everyone to have to add the custom request to their codebase themselves.

Would it make sense to add a possibility to make a GsonRequest to Volley?

**Comment by jpd236** [comment]
I don't think we would add it to the core library because we don't want everyone who uses Volley to pull in a transitive dependency on Gson even if they aren't using it. It'd be perfectly reasonable to make a second project that depends on Volley and contains GsonRequest and/or any other helper related to Gson as would be appropriate, but I don't think we have any official plans to do this at this time.
