### ISSUE TITLE
version 1.0.1 release date?

### ISSUE THREAD

**Issue by mgivi** [google/volley#97]
Any idea as when version 1.0.1 will be released?

**Comment by jpd236** [comment]
Sorry - I know it has been a while since the last release, and I would like to get the fixes we've made since 1.0.0 out there in an official form. 

I've gone ahead and created milestones for potential upcoming releases and sorted the current list of open bugs into them to try and provide a clearer finish line of sorts:

https://github.com/google/volley/milestone/1

I can't provide a concrete ETA right now, but as that list proceeds towards becoming empty, we should get closer to launch. In the mean time, it is possible to pick up the latest fixes if you are willing to be a bit more on the bleeding edge by depending on 1.0.1-SNAPSHOT releases from the  https://oss.jfrog.org/artifactory/oss-snapshot-local/ maven repository - these are automatically built after every commit to master, so they at least pass unit tests and should generally not be substantially broken for extended periods.
